// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _clock_generator_HH_
#define _clock_generator_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct clock_generator : public sc_module {
    // Port declarations 3
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_logic > out_clock;


    // Module declarations
    clock_generator(sc_module_name name);
    SC_HAS_PROCESS(clock_generator);

    ~clock_generator();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<1> > state;
    sc_signal< sc_lv<32> > counter;
    sc_signal< sc_lv<1> > select_ln21_fu_72_p3;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<32> > select_ln33_fu_58_p3;
    sc_signal< sc_lv<1> > icmp_ln33_fu_46_p2;
    sc_signal< sc_lv<32> > next_counter_fu_52_p2;
    sc_signal< sc_lv<1> > xor_ln33_fu_66_p2;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_icmp_ln33_fu_46_p2();
    void thread_next_counter_fu_52_p2();
    void thread_out_clock();
    void thread_select_ln21_fu_72_p3();
    void thread_select_ln33_fu_58_p3();
    void thread_xor_ln33_fu_66_p2();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
