set_property SRC_FILE_INFO {cfile:D:/vivado_hls/clock_generator-vhls/clock_generator.srcs/constrs_1/new/clock_generator.xdc rfile:../../../clock_generator.srcs/constrs_1/new/clock_generator.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {out_clock}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U18 [get_ports rst]
